### ISSUE TITLE
ENH: show progress bar, say how many files were read in, how processing is going

### ISSUE THREAD

**Issue by corneliusroemer** [lenaschimmel/sc2rf#16]
Would be nice to see how things are going

tqdm makes this very easy with python

a bit more logging while the analysis is going would be cool too, just so that I know what's going on, instead of seeing nothing for a minute

**Comment by lenaschimmel** [comment]
tqdm is a super nice thing! Using it when reading a file line by line is not trivial though, but I'm getting there. (Yes, the way I often use it, reading the input file is what takes the most time.)

**Comment by lenaschimmel** [comment]
Progress bars are now enabled by default (only for tasks which take longer than 200ms) and can be disabled with `--hide-progress`.
