### ISSUE TITLE
Crash related to tdqm

### ISSUE THREAD

**Issue by lenaschimmel** [lenaschimmel/sc2rf#27]
_Originally posted by @Vjimenez-vasquez in https://github.com/lenaschimmel/sc2rf/issues/25#issuecomment-1089053922_:

Hi there, 

I ran the following command : 
```r
python3 sc2rf.py test2.fasta --unique 1
```
And got the following message : 
```r
Traceback (most recent call last):
  File "sc2rf.py", line 987, in <module>
    main()
  File "sc2rf.py", line 132, in main
    reference = read_fasta('reference.fasta', None)['MN908947 (Wuhan-Hu-1/2019)']
  File "sc2rf.py", line 476, in read_fasta
    with my_tqdm(total=os.stat(path).st_size, desc="Read " + path, unit_scale=True) as pbar:
  File "sc2rf.py", line 199, in my_tqdm
    return tqdm(*margs, delay=0.1, colour="green", disable=bool(args.hide_progress), **kwargs)
  File "/home/hp/anaconda3/lib/python3.7/site-packages/tqdm/std.py", line 922, in __init__
    TqdmKeyError("Unknown argument(s): " + str(kwargs)))
tqdm.std.TqdmKeyError: "Unknown argument(s): {'delay': 0.1, 'colour': 'green'}"
```
Do you have any suggestion, please ?

**Comment by lenaschimmel** [comment]
Hi @Vjimenez-vasquez, you are not the first one to experience this problem. I had contact via Email to someone from Québec, Canada with the same crash.

It's related to `tdqm`, a library which renders progress bars, and seems to happen with certain versions of tdqm and/or certain python versions. A quick workaround is to use a previous version of Sc2rf, for example [this commit](https://github.com/lenaschimmel/sc2rf/commit/b8bee2509177df55ac14ad5148d7bf1780c145b8) which is the latest one before I added `tdqm`.

I think that you and I may have installed different versions of `tdqm`. I'm quite new to Python and the way that pip etc. work, and I don't use anaconda or miniconda. (The other person with this crash used miniconda3).

Sc2rf currently defines its dependencies / requirements in two different places:
 * [requirements.txt](https://github.com/lenaschimmel/sc2rf/blob/main/requirements.txt) - without version numbers, which I initially used
 * [setup.py](https://github.com/lenaschimmel/sc2rf/blob/main/setup.py) - with version numbers, work in progress, see #3

Do you know which of those two files were used to install the dependencies on your computer, or do you have any other information for men on how you installed it?

**Comment by Vjimenez-vasquez** [comment]
> Hi @Vjimenez-vasquez, you are not the first one to experience this problem. I had contact via Email to someone from Québec, Canada with the same crash.
> 
> It's related to `tdqm`, a library which renders progress bars, and seems to happen with certain versions of tdqm and/or certain python versions. A quick workaround is to use a previous version of Sc2rf, for example [this commit](https://github.com/lenaschimmel/sc2rf/commit/b8bee2509177df55ac14ad5148d7bf1780c145b8) which is the latest one before I added `tdqm`.
> 
> I think that you and I may have installed different versions of `tdqm`. I'm quite new to Python and the way that pip etc. work, and I don't use anaconda or miniconda. (The other person with this crash used miniconda3).
> 
> Sc2rf currently defines its dependencies / requirements in two different places:
> 
> * [requirements.txt](https://github.com/lenaschimmel/sc2rf/blob/main/requirements.txt) - without version numbers, which I initially used
> * [setup.py](https://github.com/lenaschimmel/sc2rf/blob/main/setup.py) - with version numbers, work in progress, see [Make tool pip-installable #3](https://github.com/lenaschimmel/sc2rf/issues/3)
> 
> Do you know which of those two files were used to install the dependencies on your computer, or do you have any other information for men on how you installed it?

Sure,  I used

pip3 install -r requirements.txt

**Comment by lenaschimmel** [comment]
So I just found out that the library `tdqm`added the `delay` option in version 4.48.0 and I guess you have an older version installed. My `requirements.txt` did not specify versions, but it does now. So this should probably fix it for you, @Vjimenez-vasquez.

**Comment by Vjimenez-vasquez** [comment]
@lenaschimmel, Thank you so much !! it really worked !!
