### ISSUE TITLE
--csvfile option does not work

### ISSUE THREAD

**Issue by think-o** [lenaschimmel/sc2rf#28]
Hey!

First of all, great tool to find the potential recombinants. Made my life easy.
I needed to parse the output of sc2rf only to get the potential recombinant sequences and the breakpoints of it. I see the --csvfile option in the README. But, it must not have been included in the sc2rf python executable. I get this error.

**sc2rf.py: error: unrecognized arguments: --csvfile output.csv**

Any idea if I could get the ouput in the way I need?

**Comment by think-o** [comment]
Updated it now. Have that option. Thanks

**Comment by lenaschimmel** [comment]
Ok, fine! I was just writing an answer with some more questions to understand your situation. So I'll close this now.
